pipeline {
  agent {label 'ubuntu'}
  triggers {
		githubPush()
	}
  options {
    disableConcurrentBuilds()
    buildDiscarder (logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
  } 
  parameters {
   // string(name: 'login', defaultValue: '', description: 'Enter login')
   // password(name: 'password', defaultValue: '', description: 'Enter password' )
  }

  stages {
    stage('clone') {
      //when { branch 'master' }

      steps {
        git branch: 'master',
        credentialsId: 'JenkinsRobo.onlyoffice.com',
        url: 'https://github.com/ONLYOFFICE/helm-charts.git'
      }
    }
    stage('push') {
     // when { branch 'master' }
      steps {
        withCredentials([usernamePassword(credentialsId: 'helm_repo', 
                        passwordVariable: 'password', 
                        usernameVariable: 'login')]) {
                  
        sh '''
          curl -o /tmp/helm-v3.6.1-linux-amd64.tar.gz https://get.helm.sh/helm-v3.6.1-linux-amd64.tar.gz
          ls -a /tmp
          tar -xvzf /tmp/helm-v3.6.1-linux-amd64.tar.gz -C /tmp;
          for var in $(ls -d */ | cut -f1 -d'/')
          do
            /tmp/linux-amd64/helm package $var
            curl -u ${login}:${password} http://54.76.219.80:8081/repository/helm-private/ --upload-file $var-*.tgz -v
          done
        '''
        } 
      }
    }
  }
}